# Generated by Django 3.2.5 on 2021-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='airport',
        ),
        migrations.AddField(
            model_name='agent',
            name='airport',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='app.airport'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
